dataSource:
  jdbcDriver: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost/YOUR_DB_NAME"
  username: "YOUR_DB_USERNAME"
  password: "YOUR_USER_PASSWORD"
  
pinger:  
   #the ping interval in milliseconds
   scheduledRate: 10000
   #any valid SQL query. Just make sure it will be fast enought to be completed before the next ping
   query: 'select count(*) from "USER"'
